import './globals.css'
import { Hanken_Grotesk } from "next/font/google";

const hankenGrotesk = Hanken_Grotesk({
  weight: ["500", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: 'Lucas Landin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hankenGrotesk.className}>{children}</body>
    </html>
  )
}
